name: Publish
on: [release, push]
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
      - name: Upload to Docker
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: jib -Platest=true
        env:
          DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
  publish-github:
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
      - name: Build zip
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: distZip
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          asset_path: ./build/distributions/*.zip
          asset_content_type: application/zip